// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ECXJ7O3CjSKKtqOgY6IX1C08keEvCDg',
    appId: '1:770377397693:web:bfc1ae18fda8be35894ed4',
    messagingSenderId: '770377397693',
    projectId: 'antory-5981d',
    authDomain: 'antory-5981d.firebaseapp.com',
    storageBucket: 'antory-5981d.firebasestorage.app',
    measurementId: 'G-8600N0H4JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gfzRjAfuFaR_7lauFA8cp4UcY4xQ0g4',
    appId: '1:770377397693:android:058537944ef0467e894ed4',
    messagingSenderId: '770377397693',
    projectId: 'antory-5981d',
    storageBucket: 'antory-5981d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFrDIXNfZybm6UiEfbCp9SFPjnZqm96M',
    appId: '1:770377397693:ios:9cd3976e0794c17c894ed4',
    messagingSenderId: '770377397693',
    projectId: 'antory-5981d',
    storageBucket: 'antory-5981d.firebasestorage.app',
    androidClientId: '770377397693-s10bgaldaqr74ljhbb9qorqar7icl2hv.apps.googleusercontent.com',
    iosClientId: '770377397693-n1use52m5bite74r1mch5mpo973362b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.challengeTakipFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFrDIXNfZybm6UiEfbCp9SFPjnZqm96M',
    appId: '1:770377397693:ios:9cd3976e0794c17c894ed4',
    messagingSenderId: '770377397693',
    projectId: 'antory-5981d',
    storageBucket: 'antory-5981d.firebasestorage.app',
    androidClientId: '770377397693-s10bgaldaqr74ljhbb9qorqar7icl2hv.apps.googleusercontent.com',
    iosClientId: '770377397693-n1use52m5bite74r1mch5mpo973362b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.challengeTakipFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ECXJ7O3CjSKKtqOgY6IX1C08keEvCDg',
    appId: '1:770377397693:web:cb8e06fbef5083c6894ed4',
    messagingSenderId: '770377397693',
    projectId: 'antory-5981d',
    authDomain: 'antory-5981d.firebaseapp.com',
    storageBucket: 'antory-5981d.firebasestorage.app',
    measurementId: 'G-2V25JCHP38',
  );

}